## CH0 Hello Tensorflow

In [1]:
import tensorflow as tf
import numpy as np

/home/woodylin/tensorflow3/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


### constant

In [2]:
hello_constant = tf.constant('Hello constant!')

with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello constant!'


In [3]:
# A is a 0-dimensional int32 tensor
A = tf.constant(1234) 
# B is a 1-dimensional int32 tensor
B = tf.constant([123,456,789]) 
# C is a 2-dimensional int32 tensor
C = tf.constant([ [123,456,789], [222,333,444] ])

### placeholder

In [4]:
x = tf.placeholder(tf.string)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Hello placeholder'})
    print(output)

Hello placeholder


In [5]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Test String', y: 123, z: 45.67})
    print(output)

Test String


## CH1 Tensorflow Math

In [11]:
x = tf.add(5, 2) #7 +
x = tf.subtract(10, 4) #6 -
x = tf.multiply(2, 5) #10 *
x = tf.device(10) #5 /


In [12]:
tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1))   # 1

<tf.Tensor 'Sub_4:0' shape=() dtype=int32>

### quiz : z = x / y - 1

In [13]:
# TODO: Convert the following to TensorFlow:
x = tf.constant(10.0)
y = tf.constant(2.0)
z = tf.subtract(tf.divide(x, y), 1.0)
# z = x/y - 1

# TODO: Print z from a session
with tf.Session() as sess:
    output = sess.run(z)
    print(output)

4.0


## CH2 Variables

In [14]:
x = tf.Variable(5)

In [15]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)

### normal distribtuion

The ```tf.truncated_normal()``` function returns a tensor with random values from a normal distribution whose magnitude is no more than 2 standard deviations from the mean.

In [16]:
n_features = 120
n_labels = 5
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))

The ```tf.zeros()``` function returns a tensor with all zeros.

In [17]:
n_labels = 5
bias = tf.Variable(tf.zeros(n_labels))

### Variables 運行前須先初始化

In [3]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

## CH3 Linear Function

In [24]:
def get_weights(n_features, n_labels):
    """
    Return TensorFlow weights
    :param n_features: Number of features
    :param n_labels: Number of labels
    :return: TensorFlow weights
    """
    # TODO: Return weights
    return tf.Variable(tf.truncated_normal((n_features, n_labels)))


def get_biases(n_labels):
    """
    Return TensorFlow bias
    :param n_labels: Number of labels
    :return: TensorFlow bias
    """
    # TODO: Return biases
    return tf.Variable(tf.zeros(n_labels))


def linear(input, w, b):
    """
    Return linear function in TensorFlow
    :param input: TensorFlow input
    :param w: TensorFlow weights
    :param b: TensorFlow biases
    :return: TensorFlow linear function
    """
    # TODO: Linear Function (xW + b)
    return tf.add(tf.matmul(input, w), b)

In [26]:
# Number of features (28*28 image is 784 features)
n_features = 784
# Number of labels
n_labels = 3

In [28]:
# Features and Labels
features = tf.placeholder(tf.float32)
labels = tf.placeholder(tf.float32)

In [29]:
# Weights and Biases
w = get_weights(n_features, n_labels)
b = get_biases(n_labels)

# Linear Function xW + b
logits = linear(features, w, b)

## CH4 Softmax

![Softmax](https://d17h27t6h515a5.cloudfront.net/topher/2017/August/59a3b336_softmax/softmax.png)

In [32]:
x = [3.0, 1.0, 0.2]

### numpy Softmax function

In [36]:
np.exp(x) / np.exp(x).sum(axis=0)

array([0.8360188 , 0.11314284, 0.05083836])

### Tensorflow Softmax function

In [47]:
logit_data = np.array([2.0, 1.0, 0.1]) * 10
logits = tf.placeholder(tf.float32)

softmax = tf.nn.softmax(logits)
with tf.Session() as sess:
    output = sess.run(softmax, feed_dict={logits: logit_data})
    print(output)

[9.999546e-01 4.539787e-05 5.602542e-09]


## CH5 Cross Entropy

```
tf.reduce_sum()    ex: x = tf.reduce_sum([1, 2, 3, 4, 5])  # 15
tf.log()           ex: x = tf.log(100)  # 4.60517
```

In [49]:
softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

In [69]:
cross_entropy = tf.reduce_sum(tf.multiply(one_hot_data, tf.log(one_hot_data)))

## CH6 Mini-batching

In [79]:
def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    # TODO: Implement batching
            
    output_batches = []
    
    sample_size = len(features)
    for start_i in range(0, sample_size, batch_size):
        end_i = start_i + batch_size
        batch = [features[start_i:end_i], labels[start_i:end_i]]
        output_batches.append(batch)

    return output_batches

In [80]:
example_features = [
    ['F11','F12','F13','F14'],
    ['F21','F22','F23','F24'],
    ['F31','F32','F33','F34'],
    ['F41','F42','F43','F44']]
# 4 Samples of labels
example_labels = [
    ['L11','L12'],
    ['L21','L22'],
    ['L31','L32'],
    ['L41','L42']]

example_batches = batches(3, example_features, example_labels)
print(example_batches)

[[[['F11', 'F12', 'F13', 'F14'], ['F21', 'F22', 'F23', 'F24'], ['F31', 'F32', 'F33', 'F34']], [['L11', 'L12'], ['L21', 'L22'], ['L31', 'L32']]], [[['F41', 'F42', 'F43', 'F44']], [['L41', 'L42']]]]


## CH7 ReLU

```output = tf.nn.relu(hidden_layer)```

## CH8 Deep Neural Network

Two layer neural network
![](https://d17h27t6h515a5.cloudfront.net/topher/2016/October/580fe8f8_multi-layer/multi-layer.png)

In [23]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# Parameters
learning_rate = 0.001
training_epochs = 20
batch_size = 128  # Decrease batch size if you don't have enough memory
display_step = 1

n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)
n_hidden_layer = 256 # layer number of features

In [24]:
# Store layers weight & bias
weights = {
    'hidden_layer': tf.Variable(tf.random_normal([n_input, n_hidden_layer])),
    'out': tf.Variable(tf.random_normal([n_hidden_layer, n_classes]))
}
biases = {
    'hidden_layer': tf.Variable(tf.random_normal([n_hidden_layer])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

In [25]:
# dataset
mnist = input_data.read_data_sets(".", one_hot=True, reshape=False)

# tf Graph input
x = tf.placeholder("float", [None, 28, 28, 1])
y = tf.placeholder("float", [None, n_classes])

x_flat = tf.reshape(x, [-1, n_input])

Extracting ./train-images-idx3-ubyte.gz
Extracting ./train-labels-idx1-ubyte.gz
Extracting ./t10k-images-idx3-ubyte.gz
Extracting ./t10k-labels-idx1-ubyte.gz


In [26]:
# Hidden layer with RELU activation
layer_1 = tf.add(tf.matmul(x_flat, weights['hidden_layer']),\
    biases['hidden_layer'])
layer_1 = tf.nn.relu(layer_1)
# Output layer with linear activation
logits = tf.add(tf.matmul(layer_1, weights['out']), biases['out'])

In [27]:
# Define loss and optimizer
cost = tf.reduce_mean(\
    tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)\
    .minimize(cost)

In [29]:
# Initializing the variables
init = tf.global_variables_initializer()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    # Training cycle
    for epoch in range(training_epochs):
        total_batch = int(mnist.train.num_examples/batch_size)
        # Loop over all batches
        for i in range(total_batch):
            batch_x, batch_y = mnist.train.next_batch(batch_size)
            # Run optimization op (backprop) and cost op (to get loss value)
            sess.run(optimizer, feed_dict={x: batch_x, y: batch_y})
            if i % 50 == 0:
                # to see the step improvement
                print(sess.run(cost, feed_dict={x: batch_x, y: batch_y}))

147.01367
96.27771
85.77911
69.87386
52.89007
49.851074
46.314537
48.204124
46.868725
32.291077
33.305157
33.102493
27.801777
25.823784
28.524418
32.244415
21.939499
28.488865
23.307417
20.327644
18.6446
25.905773
19.769463
22.974314
24.01738
18.539883
16.200834
19.359001
15.087596
16.299644
18.35656
12.592278
13.254843
15.816606
16.690186
10.92412
17.389334
12.71551
15.222057
21.660835
15.431204
15.164686
12.437809
13.970718
13.563839
10.75124
12.746012
12.622504
15.413525
15.688436
12.470377
15.414942
10.399273
17.516045
11.42713
12.66513
12.254402
14.391799
9.102782
8.022346
11.862504
16.277054
9.896023
13.899106
10.468024
10.74666
9.934042
9.378846
12.094387
11.922623
15.744487
14.655489
9.235741
11.377429
7.233801
12.637786
13.589088
10.573388
7.5127726
8.067748
8.981442
10.398941
10.957452
11.435812
11.877391
7.1902595
11.480488
10.264523
6.353877
8.672925
9.773172
8.836924
11.007872
10.313734
10.969325
8.356039
9.3764925
6.9340153
5.7255707
7.2284274
8.261677
7.288909
10.484992


## CH9 Save Models

**Saving Variables**

```saver = tf.train.Saver()```

```saver.save(sess, save_file)```

In [45]:
# The file path to save the data
save_file = './model.ckpt'

# Remove the previous weights and bias
tf.reset_default_graph()

# Two Tensor Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]), name='weights_0')
bias = tf.Variable(tf.truncated_normal([3]), name='bias_0')

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()

with tf.Session() as sess:
    # Initialize all the Variables
    sess.run(tf.global_variables_initializer())

    # Show the values of weights and bias
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

    # Save the model
    saver.save(sess, save_file)

Weights:
[[1.1594137  0.1921379  0.28786567]
 [1.2608308  1.1085485  1.7127745 ]]
Bias:
[-0.5795733   0.7494573   0.27507132]


**Loading Variables**

```saver = tf.train.Saver()```

```saver.restore(sess, save_file)```

In [46]:
# Remove the previous weights and bias
tf.reset_default_graph()

# Two Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]), name='weights_0')
bias = tf.Variable(tf.truncated_normal([3]), name='bias_0')

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()

with tf.Session() as sess:
    # Load the weights and bias
    saver.restore(sess, save_file)

    # Show the values of weights and bias
    print('Weight:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

INFO:tensorflow:Restoring parameters from ./model.ckpt
Weight:
[[1.1594137  0.1921379  0.28786567]
 [1.2608308  1.1085485  1.7127745 ]]
Bias:
[-0.5795733   0.7494573   0.27507132]


## CH10 Regularization

### dropout

`tf.nn.dropout`

ex: `hidden_layer = tf.nn.dropout(hidden_layer, keep_prob)`

The dropout function have two parameters:

1. `hidden_layer`: 輸入層
2. `keep_prob`: 保留多少比例的units

注意: 
訓練資料時dropout prob 為0.5 (建議)

測試資料時dropout prob 為1.0

![比對圖](https://d17h27t6h515a5.cloudfront.net/topher/2016/November/58222112_dropout-node/dropout-node.jpeg)

In [2]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf

hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[0.0, 2.0, 3.0, 4.0], [0.1, 0.2, 0.3, 0.4], [11.0, 12.0, 13.0, 14.0]])

# TODO: Create Model with Dropout
keep_prob = tf.placeholder(tf.float32)
hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_layer = tf.nn.relu(hidden_layer)
hidden_layer = tf.nn.dropout(hidden_layer, keep_prob)

output_layer =tf.add(tf.matmul(hidden_layer, weights[1]), biases[1])
# TODO: Print logits from a session
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    output = sess.run(output_layer, feed_dict={keep_prob: 0.5})
    print(output)

[[ 7.6799994 15.059999 ]
 [ 0.9100001  1.016    ]
 [ 4.72      28.32     ]]
